#lang sicp
(define (count-charge amount)
  (cc amount 5))
(define (cc amount coin)
  (cond ((= coin 0) 0)
        ((= amount 0) 1)
        ((< amount 0) 0)
        (else (+ (cc amount (- coin 1))
                 (cc (- amount (first-den coin)) coin)))))
(define (first-den coin)
  (cond ((= coin 1) 1)
        ((= coin 2) 5)
        ((= coin 3) 10)
        ((= coin 4) 25)
        ((= coin 5) 50)))
(count-charge 100)